In [1]:
import sys
sys.path.append(r'C:\Users\umang\miniconda3\envs\frozen_lake\Lib\site-packages')

import numpy as np
import gym
import time
import random
from IPython.display import clear_output

In [7]:
import numpy as np
if not hasattr(np, 'bool8'):
    np.bool8 = np.bool_

In [9]:
env = gym.make('FrozenLake-v1', render_mode='human')

In [3]:

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Algorithm Parameters

In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [10]:
rewards_all_episodes = []
# Q-learning Algorithm
for episode in range(num_episodes):
    state, _ = env.reset()

    reward_curr_episode = 0
    done = False

    for step in range(max_steps_per_episode):
        # Exploration-Exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if(exploration_rate_threshold > exploration_rate):
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, terminated, info = env.step(action)
        # Update Q-table for Q(s,a)
        q_table[state, action] = (1-learning_rate)*q_table[state, action] + learning_rate*(reward + discount_rate*np.max(q_table[new_state, :]))
        
        state = new_state
        reward_curr_episode += reward

        if done == True:
            break
    
    # Exploration Rate Decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(reward_curr_episode)
env.close()
# Calculate average reward per thousand episodes
reward_per_thousand_episode = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("*****Average Reward per Thousand Episodes*****")
for r in reward_per_thousand_episode:
    print(count, " : ", str(sum(r/1000)))
    count += 1000

# Print Q-table
print("********** Q-Table **********")
print(q_table)

KeyboardInterrupt: 

In [11]:
for episode in range(3):
    state, _ = env.reset()
    done = False
    print("**********Episode: ",episode+1,"**********")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        # clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state, reward, done, terminated, info = env.step(action)

        if done:
            # clear_output(wait=True)
            env.render()
            if reward == 1:
                print("Agent reached the goal")
                # time.sleep(3)
            else:
                print("Agent fell in a hole")
            time.sleep(3)
            # clear_output(wait=True)
            break

        state = new_state
env.close()

**********Episode:  1 **********
Agent fell in a hole
**********Episode:  2 **********
Agent reached the goal
**********Episode:  3 **********
Agent fell in a hole
